-- MySQL Script generated by MySQL Workbench
-- 10/05/15 20:31:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema grejaninexpress
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `grejaninexpress` ;

-- -----------------------------------------------------
-- Schema grejaninexpress
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grejaninexpress` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `grejaninexpress` ;

-- -----------------------------------------------------
-- Table `grejaninexpress`.`TB_GE_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grejaninexpress`.`TB_GE_USUARIO` ;

CREATE TABLE IF NOT EXISTS `grejaninexpress`.`TB_GE_USUARIO` (
  `cod_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nm_usuario` VARCHAR(120) NOT NULL COMMENT '',
  `ds_email` VARCHAR(120) NOT NULL COMMENT '',
  `ds_senha` VARCHAR(32) NOT NULL COMMENT '',
  PRIMARY KEY (`cod_usuario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grejaninexpress`.`TB_GE_ORIGEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grejaninexpress`.`TB_GE_ORIGEM` ;

CREATE TABLE IF NOT EXISTS `grejaninexpress`.`TB_GE_ORIGEM` (
  `cod_origem` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nm_origem` VARCHAR(120) NOT NULL COMMENT '',
  `ds_sigla` VARCHAR(15) NOT NULL COMMENT '',
  `ds_obs` VARCHAR(250) NULL COMMENT '',
  PRIMARY KEY (`cod_origem`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grejaninexpress`.`TB_GE_DESTINO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grejaninexpress`.`TB_GE_DESTINO` ;

CREATE TABLE IF NOT EXISTS `grejaninexpress`.`TB_GE_DESTINO` (
  `cod_destino` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nm_origem` VARCHAR(120) NOT NULL COMMENT '',
  `ds_sigla` VARCHAR(15) NOT NULL COMMENT '',
  `ds_obs` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`cod_destino`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grejaninexpress`.`TB_GE_COLABORADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grejaninexpress`.`TB_GE_COLABORADOR` ;

CREATE TABLE IF NOT EXISTS `grejaninexpress`.`TB_GE_COLABORADOR` (
  `cod_colaborador` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nm_colaborador` VARCHAR(120) NOT NULL COMMENT '',
  `ds_email` VARCHAR(120) NOT NULL COMMENT '',
  `ds_carro` VARCHAR(20) NULL COMMENT '',
  `ds_tamanho_carro` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`cod_colaborador`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grejaninexpress`.`TB_GE_FRETE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grejaninexpress`.`TB_GE_FRETE` ;

CREATE TABLE IF NOT EXISTS `grejaninexpress`.`TB_GE_FRETE` (
  `cod_frete` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `ds_data` DATE NOT NULL COMMENT '',
  `nr_wb` NVARCHAR(200) NOT NULL COMMENT '',
  `vlr_recebido` DOUBLE NOT NULL COMMENT '',
  `vlr_pago` DOUBLE NULL COMMENT '',
  `ds_obs` VARCHAR(250) NULL COMMENT '',
  `cod_origem` INT UNSIGNED NOT NULL COMMENT '',
  `cod_destino` INT UNSIGNED NOT NULL COMMENT '',
  `cod_colaborador` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`cod_frete`)  COMMENT '',
  CONSTRAINT `FK_TB_GE_FRETE_ORIGEM`
    FOREIGN KEY (`cod_origem`)
    REFERENCES `grejaninexpress`.`TB_GE_ORIGEM` (`cod_origem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TB_GE_FRETE_DESTINO`
    FOREIGN KEY (`cod_destino`)
    REFERENCES `grejaninexpress`.`TB_GE_DESTINO` (`cod_destino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TB_GE_FRETE_COLABORADOR`
    FOREIGN KEY (`cod_colaborador`)
    REFERENCES `grejaninexpress`.`TB_GE_COLABORADOR` (`cod_colaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_TB_GE_FRETE_ORIGEM` ON `grejaninexpress`.`TB_GE_FRETE` (`cod_origem` ASC)  COMMENT '';

CREATE INDEX `FK_TB_GE_FRETE_DESTINO` ON `grejaninexpress`.`TB_GE_FRETE` (`cod_destino` ASC)  COMMENT '';

CREATE INDEX `FK_TB_GE_FRETE_COLABORADOR` ON `grejaninexpress`.`TB_GE_FRETE` (`cod_colaborador` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


SELECT f.cod_frete, f.ds_data, f.nr_wb, f.vlr_recebido, f.vlr_pago, f.ds_obs, o.nm_origen, d.nm_destino, c.nm_colaborador
FROM TB_GE_FRETE, TB_GE_ORIGEM, TB_GE_DESTINO, TB_GE_COLABORADOR
ON TB_GE_FRETE f